import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const proxiamNova = localFont({
  src: "./fonts/proximanova-regular.otf",
  variable: "--font-proxima-nova-regular",
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${proxiamNova.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
